---
# tasks file for preparing

- name: update and upgrade os
  ansible.builtin.apt:
    update_cache: yes
    upgrade: safe
    autoclean: yes
    autoremove: yes

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - iptables-persistent
    - net-tools
    - iotop
    - htop
    - bash-completion
