all:
  children:
      monitoring-servers:
        hosts:
          monitoring:
            ansible_host: 5.34.201.69
            ansible_user: monitoring
            ansible_port: 3022
      control:
        hosts:
          ubuntu-c:
            ansible_connection: local
